// <auto-generated />
using System;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MontageMonitor.Server.Infrastructure.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MontageMonitor.Server.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(MonitoringDbContext))]
    [Migration("20260904125408_AddActivityAggregationIntegrity")]
    partial class AddActivityAggregationIntegrity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MontageMonitor.Server.Domain.ActivityEvent", b =>
                {
                    b.Property<Guid>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<Guid>("AgentId")
                        .HasColumnType("uuid")
                        .HasColumnName("agent_id");

                    b.Property<Guid>("ComputerId")
                        .HasColumnType("uuid")
                        .HasColumnName("computer_id");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("event_type");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.Property<JsonDocument>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset>("ReceivedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at_utc")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("integer")
                        .HasColumnName("schema_version");

                    b.HasKey("EventId")
                        .HasName("pk_activity_events");

                    b.HasIndex("AgentId", "ReceivedAtUtc")
                        .HasDatabaseName("ix_activity_events_agent_id_received_at_utc");

                    b.HasIndex("ComputerId", "OccurredAtUtc")
                        .HasDatabaseName("ix_activity_events_computer_id_occurred_at_utc");

                    b.HasIndex("EmployeeId", "OccurredAtUtc")
                        .HasDatabaseName("ix_activity_events_employee_id_occurred_at_utc");

                    b.ToTable("activity_events", null, t =>
                        {
                            t.HasCheckConstraint("ck_activity_events_schema_version", "schema_version > 0");
                        });
                });

            modelBuilder.Entity("MontageMonitor.Server.Domain.AgentCredential", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AgentId")
                        .HasColumnType("uuid")
                        .HasColumnName("agent_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTimeOffset?>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at_utc");

                    b.Property<DateTimeOffset?>("RevokedAtUtc")
                        .IsConcurrencyToken()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at_utc");

                    b.Property<string>("SecretHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("secret_hash");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id")
                        .HasName("pk_agent_credentials");

                    b.HasIndex("AgentId", "RevokedAtUtc")
                        .HasDatabaseName("ix_agent_credentials_agent_id_revoked_at_utc");

                    b.ToTable("agent_credentials", (string)null);
                });

            modelBuilder.Entity("MontageMonitor.Server.Domain.AgentDevice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ComputerId")
                        .HasColumnType("uuid")
                        .HasColumnName("computer_id");

                    b.Property<long>("ConfigVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("config_version");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTimeOffset>("EnrolledAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("enrolled_at_utc");

                    b.Property<string>("InstalledVersion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("installed_version");

                    b.Property<DateTimeOffset?>("LastSeenAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at_utc");

                    b.Property<DateTimeOffset?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id")
                        .HasName("pk_agents");

                    b.HasIndex("ComputerId")
                        .IsUnique()
                        .HasDatabaseName("ix_agents_computer_id");

                    b.HasIndex("Status", "LastSeenAtUtc")
                        .HasDatabaseName("ix_agents_status_last_seen_at_utc");

                    b.ToTable("agents", (string)null);
                });

            modelBuilder.Entity("MontageMonitor.Server.Domain.AgentEnrollmentToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ConsumedByAgentId")
                        .HasColumnType("uuid")
                        .HasColumnName("consumed_by_agent_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at_utc");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("token_hash");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTimeOffset?>("UsedAtUtc")
                        .IsConcurrencyToken()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("used_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_agent_enrollment_tokens");

                    b.HasIndex("ConsumedByAgentId")
                        .HasDatabaseName("ix_agent_enrollment_tokens_consumed_by_agent_id");

                    b.HasIndex("CreatedByUserId")
                        .HasDatabaseName("ix_agent_enrollment_tokens_created_by_user_id");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_agent_enrollment_tokens_token_hash");

                    b.HasIndex("EmployeeId", "ExpiresAtUtc", "UsedAtUtc")
                        .HasDatabaseName("ix_agent_enrollment_tokens_employee_id_expires_at_utc_used_at_");

                    b.ToTable("agent_enrollment_tokens", null, t =>
                        {
                            t.HasCheckConstraint("ck_agent_enrollment_tokens_expiry", "expires_at_utc > created_at_utc");
                        });
                });

            modelBuilder.Entity("MontageMonitor.Server.Domain.ApplicationRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Classification")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("classification");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("display_name");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<bool>("IsScreenshotExcluded")
                        .HasColumnType("boolean")
                        .HasColumnName("is_screenshot_excluded");

                    b.Property<string>("NormalizedProcessName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("normalized_process_name");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<string>("ProcessName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("process_name");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.HasKey("Id")
                        .HasName("pk_application_rules");

                    b.HasIndex("NormalizedProcessName")
                        .IsUnique()
                        .HasDatabaseName("ix_application_rules_normalized_process_name");

                    b.HasIndex("UpdatedByUserId")
                        .HasDatabaseName("ix_application_rules_updated_by_user_id");

                    b.HasIndex("IsEnabled", "Priority")
                        .HasDatabaseName("ix_application_rules_is_enabled_priority");

                    b.ToTable("application_rules", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            Classification = "Productive",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayName = "Adobe Premiere Pro",
                            IsEnabled = true,
                            IsScreenshotExcluded = false,
                            NormalizedProcessName = "ADOBE PREMIERE PRO.EXE",
                            Priority = 0,
                            ProcessName = "Adobe Premiere Pro.exe",
                            UpdatedAtUtc = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            Classification = "Productive",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayName = "Adobe Media Encoder",
                            IsEnabled = true,
                            IsScreenshotExcluded = false,
                            NormalizedProcessName = "ADOBE MEDIA ENCODER.EXE",
                            Priority = 0,
                            ProcessName = "Adobe Media Encoder.exe",
                            UpdatedAtUtc = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000003"),
                            Classification = "Productive",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayName = "Adobe After Effects",
                            IsEnabled = true,
                            IsScreenshotExcluded = false,
                            NormalizedProcessName = "AFTERFX.EXE",
                            Priority = 0,
                            ProcessName = "AfterFX.exe",
                            UpdatedAtUtc = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000004"),
                            Classification = "Productive",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayName = "After Effects Render Engine",
                            IsEnabled = true,
                            IsScreenshotExcluded = false,
                            NormalizedProcessName = "AERENDER.EXE",
                            Priority = 0,
                            ProcessName = "aerender.exe",
                            UpdatedAtUtc = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000005"),
                            Classification = "Productive",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayName = "DaVinci Resolve",
                            IsEnabled = true,
                            IsScreenshotExcluded = false,
                            NormalizedProcessName = "RESOLVE.EXE",
                            Priority = 0,
                            ProcessName = "Resolve.exe",
                            UpdatedAtUtc = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000006"),
                            Classification = "Productive",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayName = "FFmpeg",
                            IsEnabled = true,
                            IsScreenshotExcluded = false,
                            NormalizedProcessName = "FFMPEG.EXE",
                            Priority = 0,
                            ProcessName = "ffmpeg.exe",
                            UpdatedAtUtc = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000007"),
                            Classification = "Productive",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayName = "Blender",
                            IsEnabled = true,
                            IsScreenshotExcluded = false,
                            NormalizedProcessName = "BLENDER.EXE",
                            Priority = 0,
                            ProcessName = "Blender.exe",
                            UpdatedAtUtc = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000008"),
                            Classification = "Neutral",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayName = "Google Chrome",
                            IsEnabled = true,
                            IsScreenshotExcluded = false,
                            NormalizedProcessName = "CHROME.EXE",
                            Priority = 0,
                            ProcessName = "chrome.exe",
                            UpdatedAtUtc = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000009"),
                            Classification = "Ignored",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayName = "1Password",
                            IsEnabled = true,
                            IsScreenshotExcluded = true,
                            NormalizedProcessName = "1PASSWORD.EXE",
                            Priority = 0,
                            ProcessName = "1Password.exe",
                            UpdatedAtUtc = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000010"),
                            Classification = "Ignored",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayName = "KeePass",
                            IsEnabled = true,
                            IsScreenshotExcluded = true,
                            NormalizedProcessName = "KEEPASS.EXE",
                            Priority = 0,
                            ProcessName = "KeePass.exe",
                            UpdatedAtUtc = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("MontageMonitor.Server.Domain.ApplicationSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Classification")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("classification");

                    b.Property<Guid>("ComputerId")
                        .HasColumnType("uuid")
                        .HasColumnName("computer_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id");

                    b.Property<DateTimeOffset?>("EndedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ended_at_utc");

                    b.Property<string>("ExecutablePath")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("executable_path");

                    b.Property<string>("ProcessName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("process_name");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at_utc");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("WindowTitle")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("window_title");

                    b.HasKey("Id")
                        .HasName("pk_application_sessions");

                    b.HasIndex("ComputerId")
                        .IsUnique()
                        .HasDatabaseName("ix_application_sessions_computer_id")
                        .HasFilter("ended_at_utc IS NULL");

                    b.HasIndex("ComputerId", "StartedAtUtc")
                        .HasDatabaseName("ix_application_sessions_computer_id_started_at_utc");

                    b.HasIndex("EmployeeId", "StartedAtUtc")
                        .HasDatabaseName("ix_application_sessions_employee_id_started_at_utc");

                    b.HasIndex("EmployeeId", "ProcessName", "StartedAtUtc")
                        .HasDatabaseName("ix_application_sessions_employee_id_process_name_started_at_utc");

                    b.ToTable("application_sessions", null, t =>
                        {
                            t.HasCheckConstraint("ck_application_sessions_time", "ended_at_utc IS NULL OR ended_at_utc >= started_at_utc");
                        });
                });

            modelBuilder.Entity("MontageMonitor.Server.Domain.AuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("action");

                    b.Property<JsonDocument>("Details")
                        .HasColumnType("jsonb")
                        .HasColumnName("details");

                    b.Property<string>("EntityId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("entity_name");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("ip_address");

                    b.Property<DateTimeOffset>("TimestampUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp_utc")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_audit_logs");

                    b.HasIndex("TimestampUtc")
                        .HasDatabaseName("ix_audit_logs_timestamp_utc");

                    b.HasIndex("EntityName", "EntityId")
                        .HasDatabaseName("ix_audit_logs_entity_name_entity_id");

                    b.HasIndex("UserId", "TimestampUtc")
                        .HasDatabaseName("ix_audit_logs_user_id_timestamp_utc");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("MontageMonitor.Server.Domain.Computer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AgentVersion")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("agent_version");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean")
                        .HasColumnName("is_revoked");

                    b.Property<DateTimeOffset?>("LastHeartbeatAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_heartbeat_at_utc");

                    b.Property<string>("LastIpAddress")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("last_ip_address");

                    b.Property<DateTimeOffset?>("LastOnlineAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_online_at_utc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("normalized_name");

                    b.Property<string>("OperatingSystem")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("operating_system");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id")
                        .HasName("pk_computers");

                    b.HasIndex("LastHeartbeatAtUtc")
                        .HasDatabaseName("ix_computers_last_heartbeat_at_utc");

                    b.HasIndex("EmployeeId", "NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("ix_computers_employee_id_normalized_name");

                    b.ToTable("computers", null, t =>
                        {
                            t.HasCheckConstraint("ck_computers_normalized_name", "normalized_name <> ''");
                        });
                });

            modelBuilder.Entity("MontageMonitor.Server.Domain.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Department")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("department");

                    b.Property<int>("IdleThresholdSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("idle_threshold_seconds");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("login");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedLogin")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("normalized_login");

                    b.Property<bool>("ScreenshotEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("screenshot_enabled");

                    b.Property<int>("ScreenshotIntervalMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("screenshot_interval_minutes");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id")
                        .HasName("pk_employees");

                    b.HasIndex("NormalizedLogin")
                        .IsUnique()
                        .HasDatabaseName("ix_employees_normalized_login");

                    b.HasIndex("IsActive", "Name")
                        .HasDatabaseName("ix_employees_is_active_name");

                    b.ToTable("employees", null, t =>
                        {
                            t.HasCheckConstraint("ck_employees_idle_threshold", "idle_threshold_seconds >= 0");

                            t.HasCheckConstraint("ck_employees_screenshot_interval", "screenshot_interval_minutes BETWEEN 1 AND 60");
                        });
                });

            modelBuilder.Entity("MontageMonitor.Server.Domain.Heartbeat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AgentId")
                        .HasColumnType("uuid")
                        .HasColumnName("agent_id");

                    b.Property<string>("AgentVersion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("agent_version");

                    b.Property<Guid>("ComputerId")
                        .HasColumnType("uuid")
                        .HasColumnName("computer_id");

                    b.Property<double>("CpuLoadPercent")
                        .HasColumnType("double precision")
                        .HasColumnName("cpu_load_percent");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<string>("ForegroundExecutablePath")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("foreground_executable_path");

                    b.Property<string>("ForegroundProcess")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("foreground_process");

                    b.Property<string>("ForegroundWindowTitle")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("foreground_window_title");

                    b.Property<string>("HumanState")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("human_state");

                    b.Property<int>("IdleSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("idle_seconds");

                    b.Property<string>("MachineName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("machine_name");

                    b.Property<string>("MachineState")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("machine_state");

                    b.Property<double>("MemoryLoadPercent")
                        .HasColumnType("double precision")
                        .HasColumnName("memory_load_percent");

                    b.Property<DateTimeOffset>("TimestampUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp_utc");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("WindowsUser")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("windows_user");

                    b.HasKey("Id")
                        .HasName("pk_heartbeats");

                    b.HasIndex("AgentId")
                        .HasDatabaseName("ix_heartbeats_agent_id");

                    b.HasIndex("EventId")
                        .IsUnique()
                        .HasDatabaseName("ix_heartbeats_event_id");

                    b.HasIndex("ComputerId", "TimestampUtc")
                        .HasDatabaseName("ix_heartbeats_computer_id_timestamp_utc");

                    b.HasIndex("EmployeeId", "TimestampUtc")
                        .HasDatabaseName("ix_heartbeats_employee_id_timestamp_utc");

                    b.ToTable("heartbeats", null, t =>
                        {
                            t.HasCheckConstraint("ck_heartbeats_cpu", "cpu_load_percent BETWEEN 0 AND 100");

                            t.HasCheckConstraint("ck_heartbeats_identity_text", "agent_version <> '' AND windows_user <> '' AND machine_name <> ''");

                            t.HasCheckConstraint("ck_heartbeats_idle", "idle_seconds >= 0");

                            t.HasCheckConstraint("ck_heartbeats_memory", "memory_load_percent BETWEEN 0 AND 100");
                        });
                });

            modelBuilder.Entity("MontageMonitor.Server.Domain.HumanStateSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ComputerId")
                        .HasColumnType("uuid")
                        .HasColumnName("computer_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id");

                    b.Property<DateTimeOffset?>("EndedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ended_at_utc");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at_utc");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("state");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id")
                        .HasName("pk_human_state_sessions");

                    b.HasIndex("ComputerId")
                        .IsUnique()
                        .HasDatabaseName("ix_human_state_sessions_computer_id")
                        .HasFilter("ended_at_utc IS NULL");

                    b.HasIndex("ComputerId", "StartedAtUtc")
                        .HasDatabaseName("ix_human_state_sessions_computer_id_started_at_utc");

                    b.HasIndex("EmployeeId", "StartedAtUtc")
                        .HasDatabaseName("ix_human_state_sessions_employee_id_started_at_utc");

                    b.HasIndex("EmployeeId", "State", "StartedAtUtc")
                        .HasDatabaseName("ix_human_state_sessions_employee_id_state_started_at_utc");

                    b.ToTable("human_state_sessions", null, t =>
                        {
                            t.HasCheckConstraint("ck_human_state_sessions_time", "ended_at_utc IS NULL OR ended_at_utc >= started_at_utc");
                        });
                });

            modelBuilder.Entity("MontageMonitor.Server.Domain.MachineStateSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ComputerId")
                        .HasColumnType("uuid")
                        .HasColumnName("computer_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<byte>("DetectionConfidence")
                        .HasColumnType("smallint")
                        .HasColumnName("detection_confidence");

                    b.Property<string>("DetectionReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("detection_reason");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id");

                    b.Property<DateTimeOffset?>("EndedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ended_at_utc");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at_utc");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("state");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id")
                        .HasName("pk_machine_state_sessions");

                    b.HasIndex("ComputerId")
                        .IsUnique()
                        .HasDatabaseName("ix_machine_state_sessions_computer_id")
                        .HasFilter("ended_at_utc IS NULL");

                    b.HasIndex("ComputerId", "StartedAtUtc")
                        .HasDatabaseName("ix_machine_state_sessions_computer_id_started_at_utc");

                    b.HasIndex("EmployeeId", "StartedAtUtc")
                        .HasDatabaseName("ix_machine_state_sessions_employee_id_started_at_utc");

                    b.HasIndex("EmployeeId", "State", "StartedAtUtc")
                        .HasDatabaseName("ix_machine_state_sessions_employee_id_state_started_at_utc");

                    b.ToTable("machine_state_sessions", null, t =>
                        {
                            t.HasCheckConstraint("ck_machine_state_sessions_confidence", "detection_confidence BETWEEN 0 AND 100");

                            t.HasCheckConstraint("ck_machine_state_sessions_time", "ended_at_utc IS NULL OR ended_at_utc >= started_at_utc");
                        });
                });

            modelBuilder.Entity("MontageMonitor.Server.Domain.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at_utc");

                    b.Property<Guid?>("ReplacedByTokenId")
                        .HasColumnType("uuid")
                        .HasColumnName("replaced_by_token_id");

                    b.Property<DateTimeOffset?>("RevokedAtUtc")
                        .IsConcurrencyToken()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at_utc");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("token_hash");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_refresh_tokens");

                    b.HasIndex("ReplacedByTokenId")
                        .HasDatabaseName("ix_refresh_tokens_replaced_by_token_id");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_refresh_tokens_token_hash");

                    b.HasIndex("UserId", "ExpiresAtUtc")
                        .HasDatabaseName("ix_refresh_tokens_user_id_expires_at_utc");

                    b.ToTable("refresh_tokens", null, t =>
                        {
                            t.HasCheckConstraint("ck_refresh_tokens_expiry", "expires_at_utc > created_at_utc");
                        });
                });

            modelBuilder.Entity("MontageMonitor.Server.Domain.RenderRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("ConfirmationSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("confirmation_seconds");

                    b.Property<double>("CpuThresholdPercent")
                        .HasColumnType("double precision")
                        .HasColumnName("cpu_threshold_percent");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<long>("DiskWriteThresholdBytesPerSecond")
                        .HasColumnType("bigint")
                        .HasColumnName("disk_write_threshold_bytes_per_second");

                    b.PrimitiveCollection<string[]>("FileNamePatterns")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("file_name_patterns");

                    b.Property<int>("FinishTimeoutSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("finish_timeout_seconds");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<byte>("MinimumConfidence")
                        .HasColumnType("smallint")
                        .HasColumnName("minimum_confidence");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("ProcessName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("process_name");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.HasKey("Id")
                        .HasName("pk_render_rules");

                    b.HasIndex("UpdatedByUserId")
                        .HasDatabaseName("ix_render_rules_updated_by_user_id");

                    b.HasIndex("IsEnabled", "Type", "ProcessName")
                        .HasDatabaseName("ix_render_rules_is_enabled_type_process_name");

                    b.ToTable("render_rules", null, t =>
                        {
                            t.HasCheckConstraint("ck_render_rules_confidence", "minimum_confidence BETWEEN 0 AND 100");

                            t.HasCheckConstraint("ck_render_rules_confirmation", "confirmation_seconds > 0");

                            t.HasCheckConstraint("ck_render_rules_cpu", "cpu_threshold_percent BETWEEN 0 AND 100");

                            t.HasCheckConstraint("ck_render_rules_disk", "disk_write_threshold_bytes_per_second >= 0");

                            t.HasCheckConstraint("ck_render_rules_finish", "finish_timeout_seconds > 0");
                        });
                });

            modelBuilder.Entity("MontageMonitor.Server.Domain.RenderSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<double?>("AverageCpuPercent")
                        .HasColumnType("double precision")
                        .HasColumnName("average_cpu_percent");

                    b.Property<Guid>("ComputerId")
                        .HasColumnType("uuid")
                        .HasColumnName("computer_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<byte>("DetectionConfidence")
                        .HasColumnType("smallint")
                        .HasColumnName("detection_confidence");

                    b.Property<string>("DetectionReason")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("detection_reason");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id");

                    b.Property<DateTimeOffset?>("EndedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ended_at_utc");

                    b.Property<long?>("FileSizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size_bytes");

                    b.Property<double?>("MaxCpuPercent")
                        .HasColumnType("double precision")
                        .HasColumnName("max_cpu_percent");

                    b.Property<string>("OutputFile")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("output_file");

                    b.Property<string>("OutputFolder")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("output_folder");

                    b.Property<string>("Program")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("program");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at_utc");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id")
                        .HasName("pk_render_sessions");

                    b.HasIndex("ComputerId", "StartedAtUtc")
                        .HasDatabaseName("ix_render_sessions_computer_id_started_at_utc");

                    b.HasIndex("EmployeeId", "StartedAtUtc")
                        .HasDatabaseName("ix_render_sessions_employee_id_started_at_utc");

                    b.HasIndex("Type", "StartedAtUtc")
                        .HasDatabaseName("ix_render_sessions_type_started_at_utc");

                    b.ToTable("render_sessions", null, t =>
                        {
                            t.HasCheckConstraint("ck_render_sessions_confidence", "detection_confidence BETWEEN 0 AND 100");

                            t.HasCheckConstraint("ck_render_sessions_cpu", "(average_cpu_percent IS NULL OR average_cpu_percent BETWEEN 0 AND 100) AND (max_cpu_percent IS NULL OR max_cpu_percent BETWEEN 0 AND 100)");

                            t.HasCheckConstraint("ck_render_sessions_file_size", "file_size_bytes IS NULL OR file_size_bytes >= 0");

                            t.HasCheckConstraint("ck_render_sessions_time", "ended_at_utc IS NULL OR ended_at_utc >= started_at_utc");
                        });
                });

            modelBuilder.Entity("MontageMonitor.Server.Domain.Screenshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ComputerId")
                        .HasColumnType("uuid")
                        .HasColumnName("computer_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id");

                    b.Property<DateTimeOffset?>("FileDeletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("file_deleted_at_utc");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size_bytes");

                    b.Property<string>("ForegroundProcess")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("foreground_process");

                    b.Property<string>("ForegroundWindowTitle")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("foreground_window_title");

                    b.Property<int>("Height")
                        .HasColumnType("integer")
                        .HasColumnName("height");

                    b.Property<string>("HumanState")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("human_state");

                    b.Property<string>("MachineState")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("machine_state");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("mime_type");

                    b.Property<int>("ScreenIndex")
                        .HasColumnType("integer")
                        .HasColumnName("screen_index");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("storage_path");

                    b.Property<DateTimeOffset>("TimestampUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp_utc");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("Width")
                        .HasColumnType("integer")
                        .HasColumnName("width");

                    b.HasKey("Id")
                        .HasName("pk_screenshots");

                    b.HasIndex("StoragePath")
                        .IsUnique()
                        .HasDatabaseName("ix_screenshots_storage_path");

                    b.HasIndex("ComputerId", "TimestampUtc")
                        .HasDatabaseName("ix_screenshots_computer_id_timestamp_utc");

                    b.HasIndex("EmployeeId", "TimestampUtc")
                        .HasDatabaseName("ix_screenshots_employee_id_timestamp_utc");

                    b.HasIndex("TimestampUtc", "FileDeletedAtUtc")
                        .HasDatabaseName("ix_screenshots_timestamp_utc_file_deleted_at_utc");

                    b.ToTable("screenshots", null, t =>
                        {
                            t.HasCheckConstraint("ck_screenshots_dimensions", "width > 0 AND height > 0");

                            t.HasCheckConstraint("ck_screenshots_file_size", "file_size_bytes >= 0");

                            t.HasCheckConstraint("ck_screenshots_screen_index", "screen_index >= 0");
                        });
                });

            modelBuilder.Entity("MontageMonitor.Server.Domain.SystemSetting", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("key");

                    b.Property<string>("JsonValue")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("json_value");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Key")
                        .HasName("pk_system_settings");

                    b.HasIndex("UpdatedByUserId")
                        .HasDatabaseName("ix_system_settings_updated_by_user_id");

                    b.ToTable("system_settings", null, t =>
                        {
                            t.HasCheckConstraint("ck_system_settings_version", "version > 0");
                        });

                    b.HasData(
                        new
                        {
                            Key = "company.timeZone",
                            JsonValue = "\"Europe/Moscow\"",
                            UpdatedAtUtc = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1L
                        },
                        new
                        {
                            Key = "agent.heartbeatIntervalSeconds",
                            JsonValue = "30",
                            UpdatedAtUtc = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1L
                        },
                        new
                        {
                            Key = "agent.syncIntervalSeconds",
                            JsonValue = "45",
                            UpdatedAtUtc = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1L
                        },
                        new
                        {
                            Key = "agent.latestVersion",
                            JsonValue = "\"0.1.0\"",
                            UpdatedAtUtc = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1L
                        },
                        new
                        {
                            Key = "activity.idleThresholdSeconds",
                            JsonValue = "300",
                            UpdatedAtUtc = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1L
                        },
                        new
                        {
                            Key = "screenshots.intervalMinutes",
                            JsonValue = "5",
                            UpdatedAtUtc = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1L
                        },
                        new
                        {
                            Key = "screenshots.retentionDays",
                            JsonValue = "30",
                            UpdatedAtUtc = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1L
                        },
                        new
                        {
                            Key = "telemetry.retentionDays",
                            JsonValue = "365",
                            UpdatedAtUtc = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1L
                        },
                        new
                        {
                            Key = "backup.retentionDays",
                            JsonValue = "14",
                            UpdatedAtUtc = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1L
                        });
                });

            modelBuilder.Entity("MontageMonitor.Server.Domain.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<int>("FailedLoginCount")
                        .HasColumnType("integer")
                        .HasColumnName("failed_login_count");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTimeOffset?>("LastLoginAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at_utc");

                    b.Property<DateTimeOffset?>("LockoutEndUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end_utc");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("login");

                    b.Property<string>("NormalizedLogin")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("normalized_login");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("NormalizedLogin")
                        .IsUnique()
                        .HasDatabaseName("ix_users_normalized_login");

                    b.ToTable("users", null, t =>
                        {
                            t.HasCheckConstraint("ck_users_failed_login_count", "failed_login_count >= 0");

                            t.HasCheckConstraint("ck_users_password_hash", "password_hash <> ''");
                        });
                });

            modelBuilder.Entity("MontageMonitor.Server.Domain.UserEmployeeAccess", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("UserId", "EmployeeId")
                        .HasName("pk_user_employee_access");

                    b.HasIndex("EmployeeId")
                        .HasDatabaseName("ix_user_employee_access_employee_id");

                    b.ToTable("user_employee_access", (string)null);
                });

            modelBuilder.Entity("MontageMonitor.Server.Domain.WatchedFolder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ComputerId")
                        .HasColumnType("uuid")
                        .HasColumnName("computer_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.PrimitiveCollection<string[]>("Extensions")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("extensions");

                    b.PrimitiveCollection<string[]>("FileNamePatterns")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("file_name_patterns");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<string>("PathPattern")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("path_pattern");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id")
                        .HasName("pk_watched_folders");

                    b.HasIndex("ComputerId", "Type", "IsEnabled")
                        .HasDatabaseName("ix_watched_folders_computer_id_type_is_enabled");

                    b.ToTable("watched_folders", (string)null);
                });

            modelBuilder.Entity("MontageMonitor.Server.Domain.ActivityEvent", b =>
                {
                    b.HasOne("MontageMonitor.Server.Domain.AgentDevice", null)
                        .WithMany()
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_activity_events_agents_agent_id");

                    b.HasOne("MontageMonitor.Server.Domain.Computer", null)
                        .WithMany()
                        .HasForeignKey("ComputerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_activity_events_computers_computer_id");

                    b.HasOne("MontageMonitor.Server.Domain.Employee", null)
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_activity_events_employees_employee_id");
                });

            modelBuilder.Entity("MontageMonitor.Server.Domain.AgentCredential", b =>
                {
                    b.HasOne("MontageMonitor.Server.Domain.AgentDevice", null)
                        .WithMany()
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_agent_credentials_agents_agent_id");
                });

            modelBuilder.Entity("MontageMonitor.Server.Domain.AgentDevice", b =>
                {
                    b.HasOne("MontageMonitor.Server.Domain.Computer", null)
                        .WithOne()
                        .HasForeignKey("MontageMonitor.Server.Domain.AgentDevice", "ComputerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_agents_computers_computer_id");
                });

            modelBuilder.Entity("MontageMonitor.Server.Domain.AgentEnrollmentToken", b =>
                {
                    b.HasOne("MontageMonitor.Server.Domain.AgentDevice", null)
                        .WithMany()
                        .HasForeignKey("ConsumedByAgentId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_agent_enrollment_tokens_agents_consumed_by_agent_id");

                    b.HasOne("MontageMonitor.Server.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_agent_enrollment_tokens_users_created_by_user_id");

                    b.HasOne("MontageMonitor.Server.Domain.Employee", null)
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_agent_enrollment_tokens_employees_employee_id");
                });

            modelBuilder.Entity("MontageMonitor.Server.Domain.ApplicationRule", b =>
                {
                    b.HasOne("MontageMonitor.Server.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_application_rules_users_updated_by_user_id");
                });

            modelBuilder.Entity("MontageMonitor.Server.Domain.ApplicationSession", b =>
                {
                    b.HasOne("MontageMonitor.Server.Domain.Computer", null)
                        .WithMany()
                        .HasForeignKey("ComputerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_application_sessions_computers_computer_id");

                    b.HasOne("MontageMonitor.Server.Domain.Employee", null)
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_application_sessions_employees_employee_id");
                });

            modelBuilder.Entity("MontageMonitor.Server.Domain.AuditLog", b =>
                {
                    b.HasOne("MontageMonitor.Server.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_audit_logs_users_user_id");
                });

            modelBuilder.Entity("MontageMonitor.Server.Domain.Computer", b =>
                {
                    b.HasOne("MontageMonitor.Server.Domain.Employee", null)
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_computers_employees_employee_id");
                });

            modelBuilder.Entity("MontageMonitor.Server.Domain.Heartbeat", b =>
                {
                    b.HasOne("MontageMonitor.Server.Domain.AgentDevice", null)
                        .WithMany()
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_heartbeats_agents_agent_id");

                    b.HasOne("MontageMonitor.Server.Domain.Computer", null)
                        .WithMany()
                        .HasForeignKey("ComputerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_heartbeats_computers_computer_id");

                    b.HasOne("MontageMonitor.Server.Domain.Employee", null)
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_heartbeats_employees_employee_id");
                });

            modelBuilder.Entity("MontageMonitor.Server.Domain.HumanStateSession", b =>
                {
                    b.HasOne("MontageMonitor.Server.Domain.Computer", null)
                        .WithMany()
                        .HasForeignKey("ComputerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_human_state_sessions_computers_computer_id");

                    b.HasOne("MontageMonitor.Server.Domain.Employee", null)
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_human_state_sessions_employees_employee_id");
                });

            modelBuilder.Entity("MontageMonitor.Server.Domain.MachineStateSession", b =>
                {
                    b.HasOne("MontageMonitor.Server.Domain.Computer", null)
                        .WithMany()
                        .HasForeignKey("ComputerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_machine_state_sessions_computers_computer_id");

                    b.HasOne("MontageMonitor.Server.Domain.Employee", null)
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_machine_state_sessions_employees_employee_id");
                });

            modelBuilder.Entity("MontageMonitor.Server.Domain.RefreshToken", b =>
                {
                    b.HasOne("MontageMonitor.Server.Domain.RefreshToken", null)
                        .WithMany()
                        .HasForeignKey("ReplacedByTokenId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_refresh_tokens_refresh_tokens_replaced_by_token_id");

                    b.HasOne("MontageMonitor.Server.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_tokens_users_user_id");
                });

            modelBuilder.Entity("MontageMonitor.Server.Domain.RenderRule", b =>
                {
                    b.HasOne("MontageMonitor.Server.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_render_rules_users_updated_by_user_id");
                });

            modelBuilder.Entity("MontageMonitor.Server.Domain.RenderSession", b =>
                {
                    b.HasOne("MontageMonitor.Server.Domain.Computer", null)
                        .WithMany()
                        .HasForeignKey("ComputerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_render_sessions_computers_computer_id");

                    b.HasOne("MontageMonitor.Server.Domain.Employee", null)
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_render_sessions_employees_employee_id");
                });

            modelBuilder.Entity("MontageMonitor.Server.Domain.Screenshot", b =>
                {
                    b.HasOne("MontageMonitor.Server.Domain.Computer", null)
                        .WithMany()
                        .HasForeignKey("ComputerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_screenshots_computers_computer_id");

                    b.HasOne("MontageMonitor.Server.Domain.Employee", null)
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_screenshots_employees_employee_id");
                });

            modelBuilder.Entity("MontageMonitor.Server.Domain.SystemSetting", b =>
                {
                    b.HasOne("MontageMonitor.Server.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_system_settings_users_updated_by_user_id");
                });

            modelBuilder.Entity("MontageMonitor.Server.Domain.UserEmployeeAccess", b =>
                {
                    b.HasOne("MontageMonitor.Server.Domain.Employee", null)
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_employee_access_employees_employee_id");

                    b.HasOne("MontageMonitor.Server.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_employee_access_users_user_id");
                });

            modelBuilder.Entity("MontageMonitor.Server.Domain.WatchedFolder", b =>
                {
                    b.HasOne("MontageMonitor.Server.Domain.Computer", null)
                        .WithMany()
                        .HasForeignKey("ComputerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_watched_folders_computers_computer_id");
                });
#pragma warning restore 612, 618
        }
    }
}
